jobs:
- job: BuildToolchain
  strategy:
      matrix:
        64bit:
          ChocoPlatform:
          MsysPath: C:\tools\msys64
          MingwPlatform: mingw64
          Platform: 64bit
  displayName: Build toolchain
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      choco install msys2 -y $(ChocoPlatform)
    displayName: 'Install msys2'
  - task: PowerShell@2
    displayName: 'Build Toolchain'
    inputs:
      targetType: filePath
      filePath: '.\build-windows-toolchain.ps1'
      arguments: -MsysPath $(MsysPath) -MingwPlatform $(MingwPlatform)
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'toolchain-$(Platform)'
      targetPath: 'artifact'
